# Generated by Django 2.0.5 on 2018-05-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='User', max_length=50, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('read', models.IntegerField(blank=True, db_column='Read', default=0, null=True)),
                ('review', models.IntegerField(blank=True, db_column='Review', default=0, null=True)),
                ('addTime', models.DateTimeField(blank=True, db_column='AddTime', null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('label', models.CharField(blank=True, db_column='Label', max_length=100, null=True)),
            ],
            options={
                'db_table': 't_content',
            },
        ),
    ]
