# Generated by Django 2.0.5 on 2018-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcontent',
            name='id',
            field=models.IntegerField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
