# Generated by Django 2.0.5 on 2018-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0002_auto_20180521_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcontent',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
