# Generated by Django 2.0.5 on 2018-05-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0003_auto_20180521_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLink',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=150, null=True)),
                ('isdelete', models.IntegerField(blank=True, db_column='IsDelete', default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tcontent',
            name='isdelete',
            field=models.IntegerField(blank=True, db_column='IsDelete', default=1, null=True),
        ),
        migrations.AddField(
            model_name='tcontent',
            name='type',
            field=models.IntegerField(blank=True, db_column='Type', default=0, null=True),
        ),
    ]
