# Generated by Django 2.0.5 on 2018-05-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0004_auto_20180523_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tlink',
            table='t_link',
        ),
    ]
