# Generated by Django 2.0.5 on 2018-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0005_auto_20180523_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='TImage',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('isdelete', models.IntegerField(blank=True, db_column='IsDelete', default=1, null=True)),
            ],
            options={
                'db_table': 't_image',
            },
        ),
    ]
