# Generated by Django 2.0.5 on 2018-06-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0006_timage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcontent',
            name='img',
            field=models.CharField(blank=True, db_column='Img', max_length=50, null=True),
        ),
    ]
