# Generated by Django 2.0.5 on 2018-06-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0007_tcontent_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMood',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('addTime', models.DateTimeField(blank=True, db_column='AddTime', null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('isdelete', models.IntegerField(blank=True, db_column='IsDelete', default=1, null=True)),
                ('img', models.CharField(blank=True, db_column='Img', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_mood',
            },
        ),
    ]
