# Generated by Django 2.0.5 on 2018-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPro', '0008_tmood'),
    ]

    operations = [
        migrations.CreateModel(
            name='TComment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('addTime', models.DateTimeField(blank=True, db_column='AddTime', null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('isdelete', models.IntegerField(blank=True, db_column='IsDelete', default=1)),
                ('countid', models.IntegerField(db_column='CountId')),
            ],
        ),
    ]
