# Generated by Django 2.0.5 on 2018-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('pwd', models.CharField(blank=True, db_column='Pwd', max_length=100, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, db_column='Phone', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
