# Generated by Django 2.0.5 on 2018-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=20, null=True),
        ),
    ]
