# Generated by Django 2.0.5 on 2018-06-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0002_auto_20180601_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='count',
            field=models.IntegerField(blank=True, db_column='Count', default=0),
        ),
    ]
