# Generated by Django 2.0.5 on 2018-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0004_tuser_logintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='loginip',
            field=models.CharField(blank=True, db_column='LoginIp', max_length=20, null=True),
        ),
    ]
