# Generated by Django 2.0.5 on 2018-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0005_tuser_loginip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='previp',
            field=models.CharField(blank=True, db_column='PrevIp', max_length=20, null=True),
        ),
    ]
